sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=b80cc9abeed21ed522cf2d3831da7ed52dfd6e18bdce2ade4125fd033e96a951
language: ruby
cache: bundler
rvm:
  - 2.6.5
before_install: gem install bundler
services:
  - docker
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_deploy:
  - docker build -f Dockerfile.prod -t babywearing.azurecr.io/babywearing:prod .

deploy:
  provider: script
  script: ./deploy/deploy.sh
  on:
    branch: credentials-update
